module.exports.USER_NOT_FOUND = 'User not found';
module.exports.USERNAME_MISSING_IN_QUERY = 'userName is missing in the query';
module.exports.ERROR_FETCHING_USER = 'Error fetching the user';
module.exports.ERROR_FETCHING_TWEET = 'Error fetching the tweet';
module.exports.ERROR_ADDING_TWEET = 'Error adding the tweet';
module.exports.ERROR_FETCHING_CONNECTIONS = 'Error fetching connections';
module.exports.ERROR_SAVING_USER = 'Error saving the user';
module.exports.MONGODB_CONNECTION_ESTABLISHED = 'Connected to MongoDB';
module.exports.MONGODB_CONNECTION_FAILED = 'Connection to MongoDB failed';
module.exports.ERROR_STARTING_SERVER = 'Error while starting the server';
module.exports.SERVER_STARTED = 'Server started at port: ';
module.exports.ERROR_ENCRYPTION_FAILED = 'Encryption failed';

module.exports.ERROR_FETCHING_DB = 500;
module.exports.ERROR_PARAMETER_MISSING = 404;
module.exports.NO_MATCH_FOUND_IN_DB = 500;
module.exports.SUCCESSFUL = 200;
module.exports.MISSING_USERNAME_OR_PASSWORD = 400;
module.exports.WRONG_PASSWORD = 400;
module.exports.TOKEN_NOT_IN_REQUEST = 404;
module.exports.TOKEN_AUTHENTICATION_FAILED = 403;
module.exports.TOKEN_VERIFIED = 200;
module.exports.USERNAME_ALREADY_EXISTS = 400;
module.exports.USER_CREATED_SUCCESSFULLY = 201;
module.exports.USER_CREATION_FAILED = 500;
module.exports.CONNECTIONS_FOUND = 200;
module.exports.CONNECTION_ADDED_SUCCESSFULLY = 200;
module.exports.CONNECTION_DELETED_SUCCESSFULLY = 200;
module.exports.CONNECTION_ADD_FAILED = 400;
module.exports.CONNECTION_DELETE_FAILED = 400;
module.exports.CONNECTIONS_NOT_FOUND = 500;
module.exports.TWEETS_NOT_FOUND = 500
module.exports.TWEETS_FOUND = 200;
module.exports.TWEET_NOT_FOUND = 500
module.exports.TWEET_FOUND = 200;
module.exports.TWEET_NOT_CREATED = 500
module.exports.TWEET_CREATED = 200;
module.exports.TWEET_NOT_DELETED = 500
module.exports.TWEET_DELETED = 200;
module.exports.TWEET_NOT_MODIFIED = 500
module.exports.TWEET_MODIFIED = 200;
module.exports.BASE_DIR = __dirname;
module.exports.USER_NAME_CHANGE_SUCCESSFUL = 200;
module.exports.USER_NAME_CHANGE_FAILED = 400;
module.exports.USER_PASSWORD_CHANGE_SUCCESSFUL = 200;
module.exports.USER_PASSWORD_CHANGE_FAILED = 400;
module.exports.SEARCH_SUCCESSFUL = 200;
module.exports.SEARCH_FAILED = 400;
